services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer_fastapi_app
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    command: >
        sh -c "pip install -e . &&
        gunicorn redis_demo.producer:app -w 8 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

    depends_on:
      # - postgres
      - redis
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer_log_worker
    volumes:
      - .:/app
    command: >
        sh -c "pip install -e . &&
        python /app/src/redis_demo/consumer.py"
    env_file: .env
    depends_on:
      # - postgres
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_stream
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--save", ""]

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml  # or remove this line if using defaults
  volumes:
    - ./config/loki.yaml:/etc/loki/loki.yaml

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana

volumes:
  grafana_data:
