services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer_fastapi_app
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    # command: gunicorn main:app -w 8 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    command: >
        sh -c "pip install -e . &&
        python /app/src/redis_demo/init_db.py &&
        gunicorn redis_demo.producer:app -w 8 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

    # uvicorn redis_demo.producer:app --host 0.0.0.0 --port 8000 --reload"
    # pyinstrument -o /app/profile.html -r html -m uvicorn redis_demo.producer:app --host 0.0.0.0 --port 8000 --reload"
    # pyinstrument -m uvicorn app.main:app --reload

    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer_log_worker
    volumes:
      - .:/app
    command: >
        sh -c "pip install -e . &&
        python /app/src/redis_demo/consumer.py"
    env_file: .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE__DB}
      POSTGRES_USER: ${DATABASE__USERNAME}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
    restart: unless-stopped
    command: postgres -c max_connections=2000 -c synchronous_commit=off

  redis:
    image: redis:7-alpine
    container_name: redis_stream
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--save", ""]
